services:
  api:
    build:
      context: .
      dockerfile: Dockerfile_app
    ports:
      - "8000:8000"
    environment:
      # - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      # - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_PROFILE=${AWS_PROFILE:-default}
      - AWS_REGION=${AWS_REGION:-eu-central-1}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/code/app:z
      # Mount local AWS credentials as read-only
      - ~/.aws:/root/.aws:ro
    # We override the Dockerfile CMD here to enable hot-reload during tests
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  ffmpeg:
    build:
      context: .
      dockerfile: Dockerfile_ffmpeg
    profiles:
      # This container only starts if the 'ffmpeg' profile is active
      - ffmpeg
    depends_on:
      - api
    environment:
      - VIDEO_FILE=${VIDEO_FILE}
    volumes:
      - ./tests:/tmp/tests:z
